dist: trusty

language: python

services:
  - docker

install:
  - docker build -f ./tests/Dockerfile -t linked_list_tests .

git:
  quiet: true

jobs:
  include:
    - stage: "Tests"
      name: "Google unit tests"
      script: docker run --rm -it linked_list_tests tests
    - name: "Memory footprint check"
      script: docker run --rm -it linked_list_tests mem_check
