dist: trusty

language: python

services:
  - docker

install:
  - docker build -f ./tests/Dockerfile -t linked_list_tests .

git:
  quiet: true

jobs:
  include:
    - stage: "Tests"
      script:
        - docker run --rm -it linked_list_tests all
